<a href="https://colab.research.google.com/github/mohamad6889/ANN/blob/main/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [5]:
dataset = pd.read_csv('divorce_data.csv', sep=';')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[2 2 4 ... 3 2 1]
 [4 4 4 ... 4 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [1 1 0 ... 3 0 0]
 [0 0 0 ... 4 3 1]
 [0 0 0 ... 3 3 1]]


In [7]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[-1.10049842 -0.43062816 -0.52146214 ... -1.04553597 -0.80891298
  -1.24018386]
 [-0.49455597 -0.43062816 -1.20337418 ... -1.04553597 -0.80891298
  -0.63128493]
 [-1.10049842 -1.09614441 -1.20337418 ... -0.36518721  1.20350468
  -0.63128493]
 ...
 [ 1.32327138  0.23488809  0.16044989 ...  0.99551033  0.53269879
   1.19541188]
 [-1.10049842 -1.09614441 -1.20337418 ...  0.31516156  0.53269879
  -0.02238599]
 [ 0.71732893  0.90040434  0.16044989 ...  0.99551033  1.20350468
   1.19541188]]


In [11]:
ann = tf.keras.models.Sequential()

In [19]:
ann.add(tf.keras.layers.Dense(units=54, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=54, activation='relu'))

### Adding the output layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [22]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [23]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 0.7012 - accuracy: 0.3514
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6648 - accuracy: 0.7473
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6333 - accuracy: 1.0000
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6088 - accuracy: 1.0000
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5841 - accuracy: 1.0000
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5568 - accuracy: 1.0000
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5384 - accuracy: 1.0000
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 0.5046 - accuracy: 1.0000
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5068 - accuracy: 1.0000
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4829 - accuracy: 1.0000
Epoch 11/100
5/5 [===========

In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred >= 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]]


In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[16  0]
 [ 2 16]]


0.9411764705882353